// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerMonitor.Infrastructure.Data;

#nullable disable

namespace ServerMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807180758_AddUptimeToMetricSnapshot")]
    partial class AddUptimeToMetricSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerMonitor.Domain.Entities.MetricSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskTotalGb")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsedGb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryTotalMb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryUsedMb")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UptimeSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MetricSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
